import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faHouse, faBook, faChartLine, faPhone, faGear, faUsers, faArrowRightArrowLeft } from "@fortawesome/free-solid-svg-icons";
import "./globals.css";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-background antialiased`}>
        <header className="bg-white flex justify-between shadow-md py-4 px-8">
          <h1 className="text-3xl font-bold">Test Title</h1>
          <div className="flex items-center gap-6">
            <a href="">Home</a>
            <a href="">About</a>
            <a href="">Profile</a>
          </div>
        </header>
        <main>
          <section className="relative flex flex-col bg-white max-w-md min-h-screen border-t border-border-color pt-6">
            {/* <button className="absolute top-2 -right-12 cursor-pointer p-2 bg-white rounded-full">
              <FontAwesomeIcon className="w-6 h-6" icon={faArrowRightArrowLeft} />
            </button> */}
            <a
              className="mx-2 p-2 flex items-center rounded-md hover:bg-background"
              href=""
            >
              <FontAwesomeIcon
                className="max-w-6 max-h-6 mr-2"
                size="sm"
                icon={faHouse}
              />
              Home
            </a>
            <a className="mx-2 p-2 flex items-center rounded-md hover:bg-background" href="">
              <FontAwesomeIcon
                className="max-w-6 max-h-6 mr-2"
                size="sm"
                icon={faBook}
              />
              Courses
            </a>
            <a className="mx-2 p-2 flex items-center rounded-md hover:bg-background" href="">
              <FontAwesomeIcon
                className="max-w-6 max-h-6 mr-2"
                size="sm"
                icon={faChartLine}
              />
              Attendance Reports
            </a>
            <a className="mx-2 p-2 flex items-center rounded-md hover:bg-background" href="">
              <FontAwesomeIcon
                className="max-w-6 max-h-6 mr-2"
                size="sm"
                icon={faPhone}
              />
              Devices
            </a>
            <a className="mx-2 p-2 flex items-center rounded-md hover:bg-background" href="">
              <FontAwesomeIcon
                className="max-w-6 max-h-6 mr-2"
                size="sm"
                icon={faUsers}
              />
              Rooms
            </a>
            <a className="mx-2 p-2 flex items-center rounded-md hover:bg-background" href="">
              <FontAwesomeIcon
                className="max-w-6 max-h-6 mr-2"
                size="sm"
                icon={faGear}
              />
              Settings
            </a>
          </section>
          {children}
        </main>
      </body>
    </html>
  );
}
